name: Release

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Extract tag version number
              id: get_version
              uses: battila7/get-version-action@v2

            - name: Substitute version in manifest
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'system/system.json'
              env:
                  version: ${{steps.get_version.outputs.version-without-v}}
                  url: https://github.com/${{github.repository}}
                  manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

            - name: Install dependencies and build
              run: |
                  npm ci
                  npm run build:production

            - name: Create system zip
              run: zip -r system.zip dist/* LICENSE README.md

            - name: Update release with files
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  name: ${{ github.event.release.name }}
                  draft: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: './dist/system.json, ./system.zip'
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}
